server:
  port: 9000

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: jarcher
    password: pass

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
